name: PYTHON ACTION

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install depencies
      run: pip install -r requirements.txt

    - name: Run lint
      run: pylint main.py
    
    - name: Run tests
      run: pytest test.py

  build:
    needs: test-python
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build for amd64
        run: pyinstaller --onefile --distpath dist_x86_64 --target-architecture x86_64 --name python_hello_world_x86_64.out main.py

      - name: Build for arm64
        run: pyinstaller --onefile --distpath dist_arm64 --target-architecture arm64 --name python_hello_world_arm_64.out main.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python_hello_world_linux_builds
          path: |
            dist_x86_64/python_hello_world_x86_64.out
            dist_arm64/python_hello_world_arm_64.out
          retention-days: 90
